name: Update Issue Status to DONE on PR Merge into develop

on:
  pull_request:
    types: [closed]

jobs:
  update-status:
    runs-on: ubuntu-latest
    # Шаги выполняются только если PR смержен и базовая ветка — develop
    if: ${{ github.event.pull_request.merged == true && github.event.pull_request.base.ref == 'develop' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up environment variables
        run: |
          echo "TOKEN_AUTOMATIZATION=${{ secrets.TOKEN_AUTOMATIZATION }}" >> $GITHUB_ENV
          echo "ID_PROJECT_SKILLDOR=${{ secrets.ID_PROJECT_SKILLDOR }}" >> $GITHUB_ENV
          echo "ID_COLUMN_STATUS_SKILLDOR=${{ secrets.ID_COLUMN_STATUS_SKILLDOR }}" >> $GITHUB_ENV
          echo "ID_COLUMN_STATUS_DONE_SKILLDOR=${{ secrets.ID_COLUMN_STATUS_DONE_SKILLDOR }}" >> $GITHUB_ENV

      - name: Update task status to DONE
        run: |
          set -euo pipefail

          LOG_FILE="pr_done.log"
          log() {
            echo "$(date '+%Y-%m-%d %H:%M:%S') - $1" | tee -a "$LOG_FILE"
          }
          error_exit() {
            log "🚨 Ошибка: $1"
            exit 1
          }

          log "==================== Запуск workflow для обновления статуса на DONE ===================="

          CURRENT_BRANCH="${{ github.event.pull_request.head.ref }}"
          log "PR ветка: $CURRENT_BRANCH"

          # Извлечение номера задачи из имени ветки (предполагается, что номер задачи находится в третьем блоке через '-')
          ISSUE_NUMBER=$(echo "$CURRENT_BRANCH" | cut -d'-' -f3)
          if [ -z "$ISSUE_NUMBER" ]; then
            error_exit "Не удалось извлечь номер задачи из имени ветки!"
          fi
          log "Извлечён ISSUE_NUMBER: $ISSUE_NUMBER"

          # Получаем данные проекта через GraphQL-запрос
          GRAPHQL_QUERY='{"query": "query { node(id: \"'"$ID_PROJECT_SKILLDOR"'\") { ... on ProjectV2 { items(first: 100) { nodes { id content { ... on Issue { number title } } } } } } }"}'
          log "📡 Отправляем GraphQL-запрос для получения элементов проекта..."
          RESPONSE=$(curl -s -X POST https://api.github.com/graphql \
            -H "Authorization: Bearer $TOKEN_AUTOMATIZATION" \
            -H "Content-Type: application/json" \
            -d "$GRAPHQL_QUERY") || error_exit "Ошибка при выполнении GraphQL-запроса"
          if echo "$RESPONSE" | jq -e '.errors' >/dev/null; then
            error_exit "Получены ошибки от GitHub API: $(echo "$RESPONSE" | jq '.errors')"
          fi
          log "✅ Данные проекта успешно получены"

          # Поиск элемента проекта по номеру задачи
          ISSUE_ITEM_ID=$(echo "$RESPONSE" | jq -r ".data.node.items.nodes[] | select(.content.number == $ISSUE_NUMBER) | .id")
          if [ -z "$ISSUE_ITEM_ID" ] || [ "$ISSUE_ITEM_ID" == "null" ]; then
            error_exit "Issue с номером $ISSUE_NUMBER не найден в проекте!"
          fi
          log "✅ Найден ISSUE_ITEM_ID: $ISSUE_ITEM_ID"

          # Отправляем GraphQL-мутацию для обновления статуса задачи на DONE
          GRAPHQL_MUTATION='{"query": "mutation { updateProjectV2ItemFieldValue(input: { projectId: \"'"$ID_PROJECT_SKILLDOR"'\", itemId: \"'"$ISSUE_ITEM_ID"'\", fieldId: \"'"$ID_COLUMN_STATUS_SKILLDOR"'\", value: { singleSelectOptionId: \"'"$ID_COLUMN_STATUS_DONE_SKILLDOR"'\" } }) { clientMutationId } }"}'
          log "📡 Отправляем GraphQL-мутацию для обновления статуса задачи на DONE..."
          MUTATION_RESPONSE=$(curl -s -X POST https://api.github.com/graphql \
            -H "Authorization: Bearer $TOKEN_AUTOMATIZATION" \
            -H "Content-Type: application/json" \
            -d "$GRAPHQL_MUTATION") || error_exit "Ошибка при выполнении GraphQL-мутации"
          log "🔄 Ответ GitHub API:"
          echo "$MUTATION_RESPONSE" | jq . | tee -a "$LOG_FILE"
          if echo "$MUTATION_RESPONSE" | jq -e '.errors' >/dev/null; then
            error_exit "Не удалось обновить статус задачи: $(echo "$MUTATION_RESPONSE" | jq '.errors')"
          fi

          log "🎉 Статус задачи $ISSUE_NUMBER успешно обновлён на DONE"

      - name: Upload log file
        uses: actions/upload-artifact@v4
        with:
          name: pr-done-log
          path: pr_done.log
